verbs = {
// $v1        $vs       $vg         $v2        $v3
  'enter': [ 'enters', 'entering', 'entered', 'entered' ],
  'read':  [ 'reads',  'reding',   'read',    'read'    ],
  'sleep': [ 'sleeps', 'sleeping', 'slept',   'slept'   ],
  'work':  [ 'works',  'working',  'worked',  'worked'  ],
  'write': [ 'writes', 'writing',  'wrote',   'written' ],
};

tenses = {
  'statement positive past nonPerfect simple I he she it we you they': '$s $v2',
  'statement positive past nonPerfect continuous I he she it': '$s was $vg',
  'statement positive past nonPerfect continuous we you they': '$s were $vg',
  'statement positive past perfect simple I he she it we you they': '$s had $v3',
  'statement positive past perfect continuous I he she it we you they': '$s had been $vg',
  'statement positive present nonPerfect simple I we you they': '$s $v1',
  'statement positive present nonPerfect simple he she it': '$s $vs',
  'statement positive present nonPerfect continuous I': '$s am $vg',
  'statement positive present nonPerfect continuous he she it': '$s is $vg',
  'statement positive present nonPerfect continuous we you they': '$s are $vg',
  'statement positive present perfect simple I we you they': '$s have $v3',
  'statement positive present perfect simple he she it': '$s has $v3',
  'statement positive present perfect continuous I we you they': '$s have been $vg',
  'statement positive present perfect continuous he she it': '$s has been $vg',
  'statement positive future nonPerfect simple I he she it we you they': '$s will $v1',
  'statement positive future nonPerfect continuous I he she it we you they': '$s will be $vg',
  'statement positive future perfect simple I he she it we you they': '$s will have $v3',
  'statement positive future perfect continuous I he she it we you they': '$s will have been $vg',

  'statement negative past nonPerfect simple I he she it we you they': '$s did not $v1',
  'statement negative past nonPerfect continuous I he she it': '$s was not $vg',
  'statement negative past nonPerfect continuous we you they': '$s were not $vg',
  'statement negative past perfect simple I': '???',
  'statement negative past perfect simple he she it': '???',
  'statement negative past perfect simple we you they': '???',
  'statement negative past perfect continuous I': '???',
  'statement negative past perfect continuous he she it': '???',
  'statement negative past perfect continuous we you they': '???',
  'statement negative present nonPerfect simple I we you they': '$s do not $v1',
  'statement negative present nonPerfect simple he she it': '$s does not $v1',
  'statement negative present nonPerfect continuous I': '$s am not $vg',
  'statement negative present nonPerfect continuous he she it': '$s is not $vg',
  'statement negative present nonPerfect continuous we you they': '$s are not $vg',
  'statement negative present perfect simple I': '???',
  'statement negative present perfect simple he she it': '???',
  'statement negative present perfect simple we you they': '???',
  'statement negative present perfect continuous I': '???',
  'statement negative present perfect continuous he she it': '???',
  'statement negative present perfect continuous we you they': '???',
  'statement negative future nonPerfect simple I': '???',
  'statement negative future nonPerfect simple he she it': '???',
  'statement negative future nonPerfect simple we you they': '???',
  'statement negative future nonPerfect continuous I': '???',
  'statement negative future nonPerfect continuous he she it': '???',
  'statement negative future nonPerfect continuous we you they': '???',
  'statement negative future perfect simple I': '???',
  'statement negative future perfect simple he she it': '???',
  'statement negative future perfect simple we you they': '???',
  'statement negative future perfect continuous I': '???',
  'statement negative future perfect continuous he she it': '???',
  'statement negative future perfect continuous we you they': '???',

  'question positive past nonPerfect simple I he she it we you they': 'did $s $v1',
  'question positive past nonPerfect continuous I he she it': 'was $s $vg',
  'question positive past nonPerfect continuous we you they': 'were $s $vg',
  'question positive past perfect simple I': '???',
  'question positive past perfect simple he she it': '???',
  'question positive past perfect simple we you they': '???',
  'question positive past perfect continuous I': '???',
  'question positive past perfect continuous he she it': '???',
  'question positive past perfect continuous we you they': ???',
  'question positive present nonPerfect simple I we you  they': 'do $s $v1',
  'question positive present nonPerfect simple he she it': 'does $s $v1',
  'question positive present nonPerfect continuous I': 'am $s $vg',
  'question positive present nonPerfect continuous he she it': 'is $s $vg',
  'question positive present nonPerfect continuous we you they': 'are $s $vg',
  'question positive present perfect simple I': '???',
  'question positive present perfect simple he she it': '???',
  'question positive present perfect simple we you they': '???',
  'question positive present perfect continuous I': '???',
  'question positive present perfect continuous he she it': '???',
  'question positive present perfect continuous we you they': '???',
  'question positive future nonPerfect simple I': '???',
  'question positive future nonPerfect simple he she it': '???',
  'question positive future nonPerfect simple we you they': '???',
  'question positive future nonPerfect continuous I': '???',
  'question positive future nonPerfect continuous he she it': '???',
  'question positive future nonPerfect continuous we you they': '???',
  'question positive future perfect simple I': '???',
  'question positive future perfect simple he she it': '???',
  'question positive future perfect simple we you they': '???',
  'question positive future perfect continuous I': '???',
  'question positive future perfect continuous he she it': '???',
  'question positive future perfect continuous we you they': '???',

  'question negative past nonPerfect simple I he she it we you they': 'did $s not $v1',
  'question negative past nonPerfect continuous I he she it': 'was $s not $vg',
  'question negative past nonPerfect continuous we you they': 'were $s not $vg',
  'question negative past perfect simple I': '???',
  'question negative past perfect simple he she it': '???',
  'question negative past perfect simple we you they': '???',
  'question negative past perfect continuous I': '???',
  'question negative past perfect continuous he she it': '???',
  'question negative past perfect continuous we you they': '???',
  'question negative present nonPerfect simple I we you they': 'do $s not $v1',
  'question negative present nonPerfect simple he she it': 'does $s not $v1',
  'question negative present nonPerfect continuous I': 'am $s not $vg',
  'question negative present nonPerfect continuous he she it': 'is $s not $vg',
  'question negative present nonPerfect continuous we you they': 'are $s not $vg',
  'question negative present perfect simple I': '???',
  'question negative present perfect simple he she it': '???',
  'question negative present perfect simple we you they': '???',
  'question negative present perfect continuous I': '???',
  'question negative present perfect continuous he she it': '???',
  'question negative present perfect continuous we you they': '???',
  'question negative future nonPerfect simple I': '???',
  'question negative future nonPerfect simple he she it': '???',
  'question negative future nonPerfect simple we you they': '???',
  'question negative future nonPerfect continuous I': '???',
  'question negative future nonPerfect continuous he she it': '???',
  'question negative future nonPerfect continuous we you they': '???',
  'question negative future perfect simple I': '???',
  'question negative future perfect simple he she it': '???',
  'question negative future perfect simple we you they': '???',
  'question negative future perfect continuous I': '???',
  'question negative future perfect continuous he she it': '???',
  'question negative future perfect continuous we you they': '???',
};
