verbs = {
// $v1        $vs       $vg         $v2        $v3
  'enter': [ 'enters', 'entering', 'entered', 'entered' ],
  'read':  [ 'reads',  'reding',   'read',    'read'    ],
  'sleep': [ 'sleeps', 'sleeping', 'slept',   'slept'   ],
  'work':  [ 'works',  'working',  'worked',  'worked'  ],
  'write': [ 'writes', 'writing',  'wrote',   'written' ],
};

tenses = {
  'statement positive past Simple I he she it we you they': '$s $v2',
  'statement positive past Continuous I he she it': '$s was $vg',
  'statement positive past Continuous we you they': '$s were $vg',
  'statement positive past Perfect I he she it we you they': '$s had $v3',
  'statement positive past PerfectContinuous I he she it we you they': '$s had been $vg',
  'statement positive present Simple I we you they': '$s $v1',
  'statement positive present Simple he she it': '$s $vs',
  'statement positive present Continuous I': '$s am $vg',
  'statement positive present Continuous he she it': '$s is $vg',
  'statement positive present Continuous we you they': '$s are $vg',
  'statement positive present Perfect I we you they': '$s have $v3',
  'statement positive present Perfect he she it': '$s has $v3',
  'statement positive present PerfectContinuous I we you they': '$s have been $vg',
  'statement positive present PerfectContinuous he she it': '$s has been $vg',
  'statement positive future Simple I he she it we you they': '$s will $v1',
  'statement positive future Continuous I he she it we you they': '$s will be $vg',
  'statement positive future Perfect I he she it we you they': '$s will have $v3',
  'statement positive future PerfectContinuous I he she it we you they': '$s will have been $vg',

  'statement negative past Simple I he she it we you they': '$s did not $v1',
  'statement negative past Continuous I he she it': '$s was not $vg',
  'statement negative past Continuous we you they': '$s were not $vg',
  'statement negative past Perfect I': '???',
  'statement negative past Perfect he she it': '???',
  'statement negative past Perfect we you they': '???',
  'statement negative past PerfectContinuous I': '???',
  'statement negative past PerfectContinuous he she it': '???',
  'statement negative past PerfectContinuous we you they': '???',
  'statement negative present Simple I': '???',
  'statement negative present Simple he she it': '???',
  'statement negative present Simple we you they': '???',
  'statement negative present Continuous I': '???',
  'statement negative present Continuous he she it': '???',
  'statement negative present Continuous we you they': '???',
  'statement negative present Perfect I': '???',
  'statement negative present Perfect he she it': '???',
  'statement negative present Perfect we you they': '???',
  'statement negative present PerfectContinuous I': '???',
  'statement negative present PerfectContinuous he she it': '???',
  'statement negative present PerfectContinuous we you they': '???',
  'statement negative future Simple I': '???',
  'statement negative future Simple he she it': '???',
  'statement negative future Simple we you they': '???',
  'statement negative future Continuous I': '???',
  'statement negative future Continuous he she it': '???',
  'statement negative future Continuous we you they': '???',
  'statement negative future Perfect I': '???',
  'statement negative future Perfect he she it': '???',
  'statement negative future Perfect we you they': '???',
  'statement negative future PerfectContinuous I': '???',
  'statement negative future PerfectContinuous he she it': '???',
  'statement negative future PerfectContinuous we you they': '???',

  'question positive past Simple I he she it we you they': 'did $s $v1',
  'question positive past Continuous I he she it': 'was $s $vg',
  'question positive past Continuous we you they': 'were $s $vg',
  'question positive past Perfect I': '???',
  'question positive past Perfect he she it': '???',
  'question positive past Perfect we you they': '???',
  'question positive past PerfectContinuous I': '???',
  'question positive past PerfectContinuous he she it': '???',
  'question positive past PerfectContinuous we you they': '???',
  'question positive present Simple I': '???',
  'question positive present Simple he she it': '???',
  'question positive present Simple we you they': '???',
  'question positive present Continuous I': '???',
  'question positive present Continuous he she it': '???',
  'question positive present Continuous we you they': '???',
  'question positive present Perfect I': '???',
  'question positive present Perfect he she it': '???',
  'question positive present Perfect we you they': '???',
  'question positive present PerfectContinuous I': '???',
  'question positive present PerfectContinuous he she it': '???',
  'question positive present PerfectContinuous we you they': '???',
  'question positive future Simple I': '???',
  'question positive future Simple he she it': '???',
  'question positive future Simple we you they': '???',
  'question positive future Continuous I': '???',
  'question positive future Continuous he she it': '???',
  'question positive future Continuous we you they': '???',
  'question positive future Perfect I': '???',
  'question positive future Perfect he she it': '???',
  'question positive future Perfect we you they': '???',
  'question positive future PerfectContinuous I': '???',
  'question positive future PerfectContinuous he she it': '???',
  'question positive future PerfectContinuous we you they': '???',

  'question negative past Simple I he she it we you they': 'did $s not $v1',
  'question negative past Continuous I he she it': 'was $s not $vg',
  'question negative past Continuous we you they': 'were $s not $vg',
  'question negative past Perfect I': '???',
  'question negative past Perfect he she it': '???',
  'question negative past Perfect we you they': '???',
  'question negative past PerfectContinuous I': '???',
  'question negative past PerfectContinuous he she it': '???',
  'question negative past PerfectContinuous we you they': '???',
  'question negative present Simple I': '???',
  'question negative present Simple he she it': '???',
  'question negative present Simple we you they': '???',
  'question negative present Continuous I': '???',
  'question negative present Continuous he she it': '???',
  'question negative present Continuous we you they': '???',
  'question negative present Perfect I': '???',
  'question negative present Perfect he she it': '???',
  'question negative present Perfect we you they': '???',
  'question negative present PerfectContinuous I': '???',
  'question negative present PerfectContinuous he she it': '???',
  'question negative present PerfectContinuous we you they': '???',
  'question negative future Simple I': '???',
  'question negative future Simple he she it': '???',
  'question negative future Simple we you they': '???',
  'question negative future Continuous I': '???',
  'question negative future Continuous he she it': '???',
  'question negative future Continuous we you they': '???',
  'question negative future Perfect I': '???',
  'question negative future Perfect he she it': '???',
  'question negative future Perfect we you they': '???',
  'question negative future PerfectContinuous I': '???',
  'question negative future PerfectContinuous he she it': '???',
  'question negative future PerfectContinuous we you they': '???',
};
